import mongoose from 'mongoose';

const alertSchema = new mongoose.Schema({
    ashaWorkerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    alertType: {
        type: String,
        required: true,
        enum: [
            'Vaccination Due',
            'Vaccination Overdue',
            'ANC Visit Due',
            'ANC Visit Missed',
            'PNC Visit Due',
            'PNC Visit Missed',
            'High Risk Pregnancy',
            'Low Hemoglobin',
            'High Blood Pressure',
            'Underweight Child',
            'Medicine Reminder',
            'Follow-up Required',
            'Emergency',
            'Other'
        ]
    },
    priority: {
        type: String,
        enum: ['Low', 'Medium', 'High', 'Critical'],
        default: 'Medium'
    },
    patientId: { type: mongoose.Schema.Types.ObjectId, ref: 'Patient' },
    patientName: { type: String },
    message: { type: String, required: true },
    details: { type: String },
    dueDate: { type: Date },
    status: {
        type: String,
        enum: ['Active', 'Acknowledged', 'Resolved', 'Dismissed'],
        default: 'Active'
    },
    relatedRecordId: { type: mongoose.Schema.Types.ObjectId },
    relatedRecordType: { type: String }, // 'PregnancyTracking', 'Immunization', 'HealthVisit', etc.
    actionRequired: { type: String },
    createdAt: { type: Date, default: Date.now },
    acknowledgedAt: { type: Date },
    resolvedAt: { type: Date },
    autoGenerated: { type: Boolean, default: false }
});

// Index for faster queries
alertSchema.index({ ashaWorkerId: 1, status: 1, priority: -1, createdAt: -1 });
alertSchema.index({ patientId: 1 });

export default mongoose.model('Alert', alertSchema);
