import mongoose from 'mongoose';

const taskSchema = new mongoose.Schema({
    ashaWorkerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    taskType: {
        type: String,
        required: true,
        enum: [
            'Home Visit',
            'ANC Checkup',
            'PNC Checkup',
            'Vaccination Follow-up',
            'Medicine Distribution',
            'Health Education',
            'Community Survey',
            'Emergency Response',
            'Referral Follow-up',
            'Other'
        ]
    },
    priority: {
        type: String,
        enum: ['Low', 'Medium', 'High', 'Urgent'],
        default: 'Medium'
    },
    patientId: { type: mongoose.Schema.Types.ObjectId, ref: 'Patient' },
    title: { type: String, required: true },
    description: { type: String },
    dueDate: { type: Date, required: true },
    status: {
        type: String,
        enum: ['Pending', 'In Progress', 'Completed', 'Cancelled'],
        default: 'Pending'
    },
    completedDate: { type: Date },
    notes: { type: String },
    autoGenerated: { type: Boolean, default: false },
    relatedRecordId: { type: mongoose.Schema.Types.ObjectId }, // Reference to related pregnancy, immunization, etc.
    relatedRecordType: { type: String }, // 'PregnancyTracking', 'Immunization', etc.
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
});

// Auto-update status
taskSchema.pre('save', function (next) {
    if (this.completedDate && this.status !== 'Completed') {
        this.status = 'Completed';
    }
    this.updatedAt = Date.now();
    next();
});

// Index for faster queries
taskSchema.index({ ashaWorkerId: 1, status: 1, dueDate: 1 });
taskSchema.index({ patientId: 1 });

export default mongoose.model('Task', taskSchema);
