import Alert from '../models/Alert.js';
import Patient from '../models/Patient.js';

// Get all alerts for ASHA worker
export const getAlerts = async (req, res) => {
    try {
        const { status, priority, alertType } = req.query;

        const filter = { ashaWorkerId: req.user.id };
        if (status) filter.status = status;
        if (priority) filter.priority = priority;
        if (alertType) filter.alertType = alertType;

        const alerts = await Alert.find(filter)
            .populate('patientId', 'fullName age gender contactNumber')
            .sort({ priority: -1, createdAt: -1 })
            .limit(100);

        res.json(alerts);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching alerts', error: error.message });
    }
};

// Get active alerts
export const getActiveAlerts = async (req, res) => {
    try {
        const alerts = await Alert.find({
            ashaWorkerId: req.user.id,
            status: 'Active'
        })
            .populate('patientId', 'fullName age gender contactNumber')
            .sort({ priority: -1, createdAt: -1 });

        res.json(alerts);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching active alerts', error: error.message });
    }
};

// Acknowledge alert
export const acknowledgeAlert = async (req, res) => {
    try {
        const { id } = req.params;

        const alert = await Alert.findOneAndUpdate(
            { _id: id, ashaWorkerId: req.user.id },
            {
                status: 'Acknowledged',
                acknowledgedAt: new Date()
            },
            { new: true }
        ).populate('patientId', 'fullName age gender');

        if (!alert) {
            return res.status(404).json({ message: 'Alert not found' });
        }

        res.json(alert);
    } catch (error) {
        res.status(500).json({ message: 'Error acknowledging alert', error: error.message });
    }
};

// Resolve alert
export const resolveAlert = async (req, res) => {
    try {
        const { id } = req.params;

        const alert = await Alert.findOneAndUpdate(
            { _id: id, ashaWorkerId: req.user.id },
            {
                status: 'Resolved',
                resolvedAt: new Date()
            },
            { new: true }
        ).populate('patientId', 'fullName age gender');

        if (!alert) {
            return res.status(404).json({ message: 'Alert not found' });
        }

        res.json(alert);
    } catch (error) {
        res.status(500).json({ message: 'Error resolving alert', error: error.message });
    }
};

// Dismiss alert
export const dismissAlert = async (req, res) => {
    try {
        const { id } = req.params;

        const alert = await Alert.findOneAndUpdate(
            { _id: id, ashaWorkerId: req.user.id },
            {
                status: 'Dismissed'
            },
            { new: true }
        ).populate('patientId', 'fullName age gender');

        if (!alert) {
            return res.status(404).json({ message: 'Alert not found' });
        }

        res.json(alert);
    } catch (error) {
        res.status(500).json({ message: 'Error dismissing alert', error: error.message });
    }
};

// Create manual alert
export const createAlert = async (req, res) => {
    try {
        const alertData = {
            ...req.body,
            ashaWorkerId: req.user.id,
            autoGenerated: false
        };

        const alert = new Alert(alertData);
        await alert.save();

        await alert.populate('patientId', 'fullName age gender');
        res.status(201).json(alert);
    } catch (error) {
        res.status(500).json({ message: 'Error creating alert', error: error.message });
    }
};
