import HealthVisit from '../models/HealthVisit.js';
import Patient from '../models/Patient.js';
import Alert from '../models/Alert.js';

// Get all health visits for ASHA worker
export const getHealthVisits = async (req, res) => {
    try {
        const visits = await HealthVisit.find({ ashaWorkerId: req.user.id })
            .populate('patientId', 'fullName age gender contactNumber')
            .sort({ visitDate: -1 })
            .limit(50);

        res.json(visits);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching health visits', error: error.message });
    }
};

// Get health visits for a specific patient
export const getPatientVisits = async (req, res) => {
    try {
        const { patientId } = req.params;

        const visits = await HealthVisit.find({ patientId })
            .populate('ashaWorkerId', 'name')
            .sort({ visitDate: -1 });

        res.json(visits);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching patient visits', error: error.message });
    }
};

// Log a new health visit
export const createHealthVisit = async (req, res) => {
    try {
        const visitData = {
            ...req.body,
            ashaWorkerId: req.user.id
        };

        const visit = new HealthVisit(visitData);
        await visit.save();

        // Update patient's last visit date
        await Patient.findByIdAndUpdate(req.body.patientId, {
            lastVisitDate: visit.visitDate,
            nextVisitDate: visit.followUpDate
        });

        // Check for high-risk conditions and create alerts
        if (visit.vitals) {
            const alerts = [];

            // Check blood pressure
            if (visit.vitals.bloodPressure) {
                const [systolic, diastolic] = visit.vitals.bloodPressure.split('/').map(Number);
                if (systolic >= 140 || diastolic >= 90) {
                    alerts.push({
                        ashaWorkerId: req.user.id,
                        alertType: 'High Blood Pressure',
                        priority: 'High',
                        patientId: req.body.patientId,
                        message: `High BP detected: ${visit.vitals.bloodPressure}`,
                        details: 'Immediate medical attention may be required',
                        actionRequired: 'Refer to doctor or PHC',
                        autoGenerated: true
                    });
                }
            }

            // Check hemoglobin
            if (visit.vitals.hemoglobin && visit.vitals.hemoglobin < 11) {
                alerts.push({
                    ashaWorkerId: req.user.id,
                    alertType: 'Low Hemoglobin',
                    priority: 'Medium',
                    patientId: req.body.patientId,
                    message: `Low Hemoglobin: ${visit.vitals.hemoglobin} g/dL`,
                    details: 'Anemia detected',
                    actionRequired: 'Provide IFA tablets and dietary counseling',
                    autoGenerated: true
                });
            }

            // Create alerts if any
            if (alerts.length > 0) {
                await Alert.insertMany(alerts);
            }
        }

        await visit.populate('patientId', 'fullName age gender');
        res.status(201).json(visit);
    } catch (error) {
        res.status(500).json({ message: 'Error creating health visit', error: error.message });
    }
};

// Update a health visit
export const updateHealthVisit = async (req, res) => {
    try {
        const { id } = req.params;

        const visit = await HealthVisit.findOneAndUpdate(
            { _id: id, ashaWorkerId: req.user.id },
            req.body,
            { new: true }
        ).populate('patientId', 'fullName age gender');

        if (!visit) {
            return res.status(404).json({ message: 'Health visit not found' });
        }

        res.json(visit);
    } catch (error) {
        res.status(500).json({ message: 'Error updating health visit', error: error.message });
    }
};

// Delete a health visit
export const deleteHealthVisit = async (req, res) => {
    try {
        const { id } = req.params;

        const visit = await HealthVisit.findOneAndDelete({
            _id: id,
            ashaWorkerId: req.user.id
        });

        if (!visit) {
            return res.status(404).json({ message: 'Health visit not found' });
        }

        res.json({ message: 'Health visit deleted successfully' });
    } catch (error) {
        res.status(500).json({ message: 'Error deleting health visit', error: error.message });
    }
};
