import Immunization from '../models/Immunization.js';
import Patient from '../models/Patient.js';
import Alert from '../models/Alert.js';
import Task from '../models/Task.js';

// Standard immunization schedule (in days from birth)
const VACCINE_SCHEDULE = {
    'BCG': 0,
    'OPV-0': 0,
    'Hepatitis B-0': 0,
    'OPV-1': 42,
    'Pentavalent-1': 42,
    'Rotavirus-1': 42,
    'PCV-1': 42,
    'OPV-2': 70,
    'Pentavalent-2': 70,
    'Rotavirus-2': 70,
    'PCV-2': 70,
    'OPV-3': 98,
    'Pentavalent-3': 98,
    'Rotavirus-3': 98,
    'PCV-3': 98,
    'IPV': 98,
    'Measles-1': 270,
    'Vitamin A-1': 270,
    'DPT Booster-1': 540,
    'OPV Booster': 540,
    'Measles-2': 540,
    'Vitamin A-2': 540,
    'DPT Booster-2': 1825
};

// Get all immunization records for ASHA worker
export const getImmunizations = async (req, res) => {
    try {
        const immunizations = await Immunization.find({ ashaWorkerId: req.user.id })
            .populate('childId', 'fullName age gender contactNumber')
            .sort({ dateOfBirth: -1 });

        res.json(immunizations);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching immunizations', error: error.message });
    }
};

// Get immunization record for a specific child
export const getImmunizationByChild = async (req, res) => {
    try {
        const { childId } = req.params;

        const immunization = await Immunization.findOne({ childId })
            .populate('childId', 'fullName age gender contactNumber')
            .populate('ashaWorkerId', 'name phone');

        if (!immunization) {
            return res.status(404).json({ message: 'Immunization record not found' });
        }

        res.json(immunization);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching immunization', error: error.message });
    }
};

// Create new immunization record
export const createImmunization = async (req, res) => {
    try {
        const { childId, dateOfBirth } = req.body;

        // Check if record already exists
        const existing = await Immunization.findOne({ childId });
        if (existing) {
            return res.status(400).json({ message: 'Immunization record already exists for this child' });
        }

        // Generate vaccine schedule
        const vaccines = Object.entries(VACCINE_SCHEDULE).map(([name, daysFromBirth]) => {
            const scheduledDate = new Date(dateOfBirth);
            scheduledDate.setDate(scheduledDate.getDate() + daysFromBirth);

            return {
                name,
                scheduledDate,
                status: 'Pending'
            };
        });

        const immunization = new Immunization({
            childId,
            ashaWorkerId: req.user.id,
            dateOfBirth,
            vaccines
        });

        await immunization.save();

        // Create tasks for upcoming vaccines (next 30 days)
        const today = new Date();
        const thirtyDaysLater = new Date(today);
        thirtyDaysLater.setDate(thirtyDaysLater.getDate() + 30);

        const upcomingVaccines = vaccines.filter(v =>
            v.scheduledDate >= today && v.scheduledDate <= thirtyDaysLater
        );

        const tasks = upcomingVaccines.map(vaccine => ({
            ashaWorkerId: req.user.id,
            taskType: 'Vaccination Follow-up',
            priority: 'High',
            patientId: childId,
            title: `${vaccine.name} Vaccination`,
            description: `Administer ${vaccine.name} vaccine`,
            dueDate: vaccine.scheduledDate,
            autoGenerated: true,
            relatedRecordId: immunization._id,
            relatedRecordType: 'Immunization'
        }));

        if (tasks.length > 0) {
            await Task.insertMany(tasks);
        }

        await immunization.populate('childId', 'fullName age gender');
        res.status(201).json(immunization);
    } catch (error) {
        res.status(500).json({ message: 'Error creating immunization record', error: error.message });
    }
};

// Update vaccine status
export const updateVaccineStatus = async (req, res) => {
    try {
        const { id } = req.params;
        const { vaccineName, givenDate, batchNumber, administeredBy, administeredAt, adverseReaction, notes } = req.body;

        const immunization = await Immunization.findOne({
            _id: id,
            ashaWorkerId: req.user.id
        });

        if (!immunization) {
            return res.status(404).json({ message: 'Immunization record not found' });
        }

        const vaccine = immunization.vaccines.find(v => v.name === vaccineName);
        if (!vaccine) {
            return res.status(404).json({ message: 'Vaccine not found in schedule' });
        }

        vaccine.givenDate = givenDate;
        vaccine.batchNumber = batchNumber;
        vaccine.administeredBy = administeredBy;
        vaccine.administeredAt = administeredAt;
        vaccine.adverseReaction = adverseReaction;
        vaccine.notes = notes;
        vaccine.status = 'Completed';

        await immunization.save();

        // Create alert if adverse reaction reported
        if (adverseReaction) {
            await Alert.create({
                ashaWorkerId: req.user.id,
                alertType: 'Other',
                priority: 'High',
                patientId: immunization.childId,
                message: `Adverse reaction to ${vaccineName}: ${adverseReaction}`,
                actionRequired: 'Monitor child and report to doctor if symptoms persist',
                relatedRecordId: immunization._id,
                relatedRecordType: 'Immunization',
                autoGenerated: true
            });
        }

        await immunization.populate('childId', 'fullName age gender');
        res.json(immunization);
    } catch (error) {
        res.status(500).json({ message: 'Error updating vaccine status', error: error.message });
    }
};

// Add growth chart data
export const addGrowthData = async (req, res) => {
    try {
        const { id } = req.params;
        const growthData = req.body;

        const immunization = await Immunization.findOne({
            _id: id,
            ashaWorkerId: req.user.id
        });

        if (!immunization) {
            return res.status(404).json({ message: 'Immunization record not found' });
        }

        immunization.growthChart.push(growthData);
        await immunization.save();

        // Check for underweight/malnutrition
        if (growthData.nutritionalStatus &&
            ['Underweight', 'Severely Underweight', 'Wasted'].includes(growthData.nutritionalStatus)) {
            await Alert.create({
                ashaWorkerId: req.user.id,
                alertType: 'Underweight Child',
                priority: growthData.nutritionalStatus === 'Severely Underweight' ? 'Critical' : 'High',
                patientId: immunization.childId,
                message: `Child is ${growthData.nutritionalStatus}`,
                details: `Weight: ${growthData.weight}kg, Height: ${growthData.height}cm`,
                actionRequired: 'Nutritional counseling and referral to Anganwadi/NRC',
                relatedRecordId: immunization._id,
                relatedRecordType: 'Immunization',
                autoGenerated: true
            });
        }

        await immunization.populate('childId', 'fullName age gender');
        res.json(immunization);
    } catch (error) {
        res.status(500).json({ message: 'Error adding growth data', error: error.message });
    }
};
