import PregnancyTracking from '../models/PregnancyTracking.js';
import Patient from '../models/Patient.js';
import Alert from '../models/Alert.js';
import Task from '../models/Task.js';

// Get all pregnancy trackings for ASHA worker
export const getPregnancies = async (req, res) => {
    try {
        const pregnancies = await PregnancyTracking.find({
            ashaWorkerId: req.user.id,
            status: 'Active'
        })
            .populate('patientId', 'fullName age contactNumber address')
            .sort({ edd: 1 });

        res.json(pregnancies);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching pregnancies', error: error.message });
    }
};

// Get pregnancy details for a specific patient
export const getPregnancyByPatient = async (req, res) => {
    try {
        const { patientId } = req.params;

        const pregnancy = await PregnancyTracking.findOne({ patientId })
            .populate('patientId', 'fullName age contactNumber address')
            .populate('ashaWorkerId', 'name phone');

        if (!pregnancy) {
            return res.status(404).json({ message: 'Pregnancy tracking not found' });
        }

        res.json(pregnancy);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching pregnancy', error: error.message });
    }
};

// Create new pregnancy tracking
export const createPregnancy = async (req, res) => {
    try {
        const pregnancyData = {
            ...req.body,
            ashaWorkerId: req.user.id
        };

        const pregnancy = new PregnancyTracking(pregnancyData);
        await pregnancy.save();

        // Update patient status
        await Patient.findByIdAndUpdate(req.body.patientId, {
            isPregnant: true,
            assignedAshaWorker: req.user.id
        });

        // Create ANC visit tasks
        const ancTasks = [];
        const lmp = new Date(req.body.lmp);

        // Schedule 4 ANC visits
        for (let i = 1; i <= 4; i++) {
            let weeksFromLMP;
            if (i === 1) weeksFromLMP = 12;
            else if (i === 2) weeksFromLMP = 20;
            else if (i === 3) weeksFromLMP = 28;
            else weeksFromLMP = 36;

            const dueDate = new Date(lmp);
            dueDate.setDate(dueDate.getDate() + (weeksFromLMP * 7));

            ancTasks.push({
                ashaWorkerId: req.user.id,
                taskType: 'ANC Checkup',
                priority: 'High',
                patientId: req.body.patientId,
                title: `ANC Visit ${i}`,
                description: `Scheduled ANC visit ${i} at ${weeksFromLMP} weeks`,
                dueDate,
                autoGenerated: true,
                relatedRecordId: pregnancy._id,
                relatedRecordType: 'PregnancyTracking'
            });
        }

        await Task.insertMany(ancTasks);

        await pregnancy.populate('patientId', 'fullName age contactNumber');
        res.status(201).json(pregnancy);
    } catch (error) {
        res.status(500).json({ message: 'Error creating pregnancy tracking', error: error.message });
    }
};

// Add ANC visit
export const addANCVisit = async (req, res) => {
    try {
        const { id } = req.params;
        const ancVisit = req.body;

        const pregnancy = await PregnancyTracking.findOne({
            _id: id,
            ashaWorkerId: req.user.id
        });

        if (!pregnancy) {
            return res.status(404).json({ message: 'Pregnancy tracking not found' });
        }

        pregnancy.ancVisits.push(ancVisit);

        // Check for risk factors
        const alerts = [];

        if (ancVisit.hemoglobin && ancVisit.hemoglobin < 11) {
            pregnancy.riskLevel = 'Medium';
            if (!pregnancy.riskFactors.includes('Anemia')) {
                pregnancy.riskFactors.push('Anemia');
            }

            alerts.push({
                ashaWorkerId: req.user.id,
                alertType: 'Low Hemoglobin',
                priority: 'High',
                patientId: pregnancy.patientId,
                message: `Pregnant woman has low Hb: ${ancVisit.hemoglobin} g/dL`,
                actionRequired: 'Provide IFA tablets and nutritional counseling',
                relatedRecordId: pregnancy._id,
                relatedRecordType: 'PregnancyTracking',
                autoGenerated: true
            });
        }

        if (ancVisit.bp) {
            const [systolic, diastolic] = ancVisit.bp.split('/').map(Number);
            if (systolic >= 140 || diastolic >= 90) {
                pregnancy.riskLevel = 'High';
                if (!pregnancy.riskFactors.includes('Hypertension')) {
                    pregnancy.riskFactors.push('Hypertension');
                }

                alerts.push({
                    ashaWorkerId: req.user.id,
                    alertType: 'High Risk Pregnancy',
                    priority: 'Critical',
                    patientId: pregnancy.patientId,
                    message: `High BP in pregnancy: ${ancVisit.bp}`,
                    actionRequired: 'Immediate referral to hospital required',
                    relatedRecordId: pregnancy._id,
                    relatedRecordType: 'PregnancyTracking',
                    autoGenerated: true
                });
            }
        }

        await pregnancy.save();

        // Update patient risk level
        await Patient.findByIdAndUpdate(pregnancy.patientId, {
            riskLevel: pregnancy.riskLevel
        });

        // Create alerts
        if (alerts.length > 0) {
            await Alert.insertMany(alerts);
        }

        await pregnancy.populate('patientId', 'fullName age contactNumber');
        res.json(pregnancy);
    } catch (error) {
        res.status(500).json({ message: 'Error adding ANC visit', error: error.message });
    }
};

// Add PNC visit
export const addPNCVisit = async (req, res) => {
    try {
        const { id } = req.params;
        const pncVisit = req.body;

        const pregnancy = await PregnancyTracking.findOne({
            _id: id,
            ashaWorkerId: req.user.id
        });

        if (!pregnancy) {
            return res.status(404).json({ message: 'Pregnancy tracking not found' });
        }

        pregnancy.pncVisits.push(pncVisit);
        await pregnancy.save();

        await pregnancy.populate('patientId', 'fullName age contactNumber');
        res.json(pregnancy);
    } catch (error) {
        res.status(500).json({ message: 'Error adding PNC visit', error: error.message });
    }
};

// Update delivery outcome
export const updateDeliveryOutcome = async (req, res) => {
    try {
        const { id } = req.params;
        const { deliveryDate, deliveryOutcome, deliveryPlace, babyGender, babyWeight } = req.body;

        const pregnancy = await PregnancyTracking.findOneAndUpdate(
            { _id: id, ashaWorkerId: req.user.id },
            {
                deliveryDate,
                deliveryOutcome,
                deliveryPlace,
                babyGender,
                babyWeight,
                status: 'Delivered'
            },
            { new: true }
        ).populate('patientId', 'fullName age contactNumber');

        if (!pregnancy) {
            return res.status(404).json({ message: 'Pregnancy tracking not found' });
        }

        // Update patient status
        await Patient.findByIdAndUpdate(pregnancy.patientId, {
            isPregnant: false
        });

        // Create PNC visit tasks
        if (deliveryOutcome === 'Live Birth') {
            const pncTasks = [];
            const deliveryDateObj = new Date(deliveryDate);

            // Schedule 4 PNC visits (Day 3, Day 7, Day 14, Day 42)
            [3, 7, 14, 42].forEach((day, index) => {
                const dueDate = new Date(deliveryDateObj);
                dueDate.setDate(dueDate.getDate() + day);

                pncTasks.push({
                    ashaWorkerId: req.user.id,
                    taskType: 'PNC Checkup',
                    priority: 'High',
                    patientId: pregnancy.patientId,
                    title: `PNC Visit ${index + 1}`,
                    description: `Post-natal checkup on Day ${day}`,
                    dueDate,
                    autoGenerated: true,
                    relatedRecordId: pregnancy._id,
                    relatedRecordType: 'PregnancyTracking'
                });
            });

            await Task.insertMany(pncTasks);
        }

        res.json(pregnancy);
    } catch (error) {
        res.status(500).json({ message: 'Error updating delivery outcome', error: error.message });
    }
};
