import Task from '../models/Task.js';
import Patient from '../models/Patient.js';

// Get all tasks for ASHA worker
export const getTasks = async (req, res) => {
    try {
        const { status, priority } = req.query;

        const filter = { ashaWorkerId: req.user.id };
        if (status) filter.status = status;
        if (priority) filter.priority = priority;

        const tasks = await Task.find(filter)
            .populate('patientId', 'fullName age gender contactNumber')
            .sort({ priority: -1, dueDate: 1 });

        res.json(tasks);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching tasks', error: error.message });
    }
};

// Get pending tasks
export const getPendingTasks = async (req, res) => {
    try {
        const tasks = await Task.find({
            ashaWorkerId: req.user.id,
            status: { $in: ['Pending', 'In Progress'] }
        })
            .populate('patientId', 'fullName age gender contactNumber')
            .sort({ priority: -1, dueDate: 1 });

        res.json(tasks);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching pending tasks', error: error.message });
    }
};

// Get completed tasks
export const getCompletedTasks = async (req, res) => {
    try {
        const tasks = await Task.find({
            ashaWorkerId: req.user.id,
            status: 'Completed'
        })
            .populate('patientId', 'fullName age gender contactNumber')
            .sort({ completedDate: -1 })
            .limit(50);

        res.json(tasks);
    } catch (error) {
        res.status(500).json({ message: 'Error fetching completed tasks', error: error.message });
    }
};

// Create manual task
export const createTask = async (req, res) => {
    try {
        const taskData = {
            ...req.body,
            ashaWorkerId: req.user.id,
            autoGenerated: false
        };

        const task = new Task(taskData);
        await task.save();

        await task.populate('patientId', 'fullName age gender');
        res.status(201).json(task);
    } catch (error) {
        res.status(500).json({ message: 'Error creating task', error: error.message });
    }
};

// Update task
export const updateTask = async (req, res) => {
    try {
        const { id } = req.params;

        const task = await Task.findOneAndUpdate(
            { _id: id, ashaWorkerId: req.user.id },
            req.body,
            { new: true }
        ).populate('patientId', 'fullName age gender');

        if (!task) {
            return res.status(404).json({ message: 'Task not found' });
        }

        res.json(task);
    } catch (error) {
        res.status(500).json({ message: 'Error updating task', error: error.message });
    }
};

// Mark task as completed
export const completeTask = async (req, res) => {
    try {
        const { id } = req.params;
        const { notes } = req.body;

        const task = await Task.findOneAndUpdate(
            { _id: id, ashaWorkerId: req.user.id },
            {
                status: 'Completed',
                completedDate: new Date(),
                notes: notes || task.notes
            },
            { new: true }
        ).populate('patientId', 'fullName age gender');

        if (!task) {
            return res.status(404).json({ message: 'Task not found' });
        }

        res.json(task);
    } catch (error) {
        res.status(500).json({ message: 'Error completing task', error: error.message });
    }
};

// Delete task
export const deleteTask = async (req, res) => {
    try {
        const { id } = req.params;

        const task = await Task.findOneAndDelete({
            _id: id,
            ashaWorkerId: req.user.id
        });

        if (!task) {
            return res.status(404).json({ message: 'Task not found' });
        }

        res.json({ message: 'Task deleted successfully' });
    } catch (error) {
        res.status(500).json({ message: 'Error deleting task', error: error.message });
    }
};
